version: "3"
services:
       rest-api:
           container_name: rest-api
           image: rawalk/rest-api
           restart: always
           build: .
           ports:
             - "3000:3000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             ports:
               - '27018:27017'
       redis:
             image: redis:latest
             ports:
               -  "6379:6379"